
export type BerryTypes = {
  index: string,
  berryName: string,
  berryImageUri: string,
  typeName: string,
  typeImageUri: string,
}

export const berryTypes : BerryTypes[] = [
  // { index: '0', berryName: "-", typeName: "-", berryImageUri: "close-button.png", typeImageUri: "close-button.png" },
  { index: '1', berryName: "Persim", typeName: "Normal", berryImageUri: "./berries/persimberry.png", typeImageUri: "./types/normal.png" },
  { index: '2', berryName: "Leppa", typeName: "Fire", berryImageUri: "./berries/leppaberry.png", typeImageUri: "./types/fire.png" },
  { index: '3', berryName: "Oran", typeName: "Water", berryImageUri: "./berries/oranberry.png", typeImageUri: "./types/water.png" },
  { index: '4', berryName: "Grepa", typeName: "Electric", berryImageUri: "./berries/grepaberry.png", typeImageUri: "./types/electric.png" },
  { index: '5', berryName: "Durin", typeName: "Grass", berryImageUri: "./berries/durinberry.png", typeImageUri: "./types/grass.png" },
  { index: '6', berryName: "Rawst", typeName: "Ice", berryImageUri: "./berries/rawstberry.png", typeImageUri: "./types/ice.png" },
  { index: '7', berryName: "Cheri", typeName: "Fighting", berryImageUri: "./berries/cheriberry.png", typeImageUri: "./types/fighting.png" },
  { index: '8', berryName: "Chesto", typeName: "Poison", berryImageUri: "./berries/chestoberry.png", typeImageUri: "./types/poison.png" },
  { index: '9', berryName: "Figy", typeName: "Ground", berryImageUri: "./berries/figyberry.png", typeImageUri: "./types/ground.png" },
  { index: '10', berryName: "Pamtre", typeName: "Flying", berryImageUri: "./berries/pamtreberry.png", typeImageUri: "./types/flying.png" },
  { index: '11', berryName: "Mago", typeName: "Psychic", berryImageUri: "./berries/magoberry.png", typeImageUri: "./types/psychic.png" },
  { index: '12', berryName: "Lum", typeName: "Bug", berryImageUri: "./berries/lumberry.png", typeImageUri: "./types/bug.png" },
  { index: '13', berryName: "Sitrus", typeName: "Rock", berryImageUri: "./berries/sitrusberry.png", typeImageUri: "./types/rock.png" },
  { index: '14', berryName: "Bluk", typeName: "Ghost", berryImageUri: "./berries/blukberry.png", typeImageUri: "./types/ghost.png" },
  { index: '15', berryName: "Yache", typeName: "Dragon", berryImageUri: "./berries/yacheberry.png", typeImageUri: "./types/dragon.png" },
  { index: '16', berryName: "Wiki", typeName: "Dark", berryImageUri: "./berries/wikiberry.png", typeImageUri: "./types/dark.png" },
  { index: '17', berryName: "Belue", typeName: "Steel", berryImageUri: "./berries/belueberry.png", typeImageUri: "./types/steel.png" },
  { index: '18', berryName: "Pecha", typeName: "Fairy", berryImageUri: "./berries/pechaberry.png", typeImageUri: "./types/fairy.png" },
]

export type Recipe = {
  key: string,
  Type: string,
  Recipe: string,
  Apple: string,
  Honey: string,
  Milk: string,
  Ginger: string,
  Oil: string,
  Cacao: string,
  Egg: string,
  Soybeans: string,
  Potato: string,
  Tomato: string,
  Mushroom: string,
  Tail: string,
  Herb: string,
  Leek: string,
  Corn: string,
  Sausage: string,
  Coffee?: string,
  Total_ingredients: string,
}

export const enum RecipePossibility {
    Possible,
    Impossible,
    Other
}

export type Ingredient = {
  key: number,
  name: string,
  uri: string,
  active?: boolean | undefined
}

export const ingredients: Ingredient[] = [
  {key: 0, name: "Apple", uri: "./ingredients/fancyapple.png"},
  {key: 1, name: "Honey", uri: "./ingredients/honey.png"},
  {key: 2, name: "Milk", uri: "./ingredients/moomoomilk.png"},
  {key: 3, name: "Ginger", uri: "./ingredients/warmingginger.png"},
  {key: 4, name: "Oil", uri: "./ingredients/pureoil.png"},
  {key: 5, name: "Cacao", uri: "./ingredients/soothingcacao.png"},
  {key: 6, name: "Egg", uri: "./ingredients/fancyegg.png"},
  {key: 7, name: "Soybeans", uri: "./ingredients/greengrasssoybeans.png"},
  {key: 8, name: "Potato", uri: "./ingredients/softpotato.png"},
  {key: 9, name: "Tomato", uri: "./ingredients/snoozytomato.png"},
  {key: 10, name: "Mushroom", uri: "./ingredients/tastymushroom.png"},
  {key: 11, name: "Tail", uri: "./ingredients/slowpoketail.png"},
  {key: 12, name: "Herb", uri: "./ingredients/fieryherb.png"},
  {key: 13, name: "Leek", uri: "./ingredients/largeleek.png"},
  {key: 14, name: "Corn", uri: "./ingredients/greengrasscorn.png"},
  {key: 15, name: "Sausage", uri: "./ingredients/beansausage.png"},
  {key: 16, name: "Coffee", uri: "./ingredients/rousingcoffee.png"},
]

export const recipeTypes = [
    "Curries/Stews",
    "Salads",
    "Desserts/Drinks",
]

export const recipes : Recipe[] = [
  { key: '0', Type: "Curries/Stews", Recipe: "Fancy Apple Curry", Apple: "7", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '1', Type: "Curries/Stews", Recipe: "Simple Chowder", Apple: "0", Honey: "0", Milk: "7", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '2', Type: "Curries/Stews", Recipe: "Beanburger Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "7", Total_ingredients: "7",  },
  { key: '3', Type: "Curries/Stews", Recipe: "Mild Honey Curry", Apple: "0", Honey: "7", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '4', Type: "Curries/Stews", Recipe: "Solar Power Tomato Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "10", Mushroom: "0", Tail: "0", Herb: "5", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "15",  },
  { key: '5', Type: "Curries/Stews", Recipe: "Drought Katsu Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "5", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "10", Total_ingredients: "15",  },
  { key: '6', Type: "Curries/Stews", Recipe: "Hearty Cheeseburger Curry", Apple: "0", Honey: "0", Milk: "8", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "8", Total_ingredients: "16",  },
  { key: '7', Type: "Curries/Stews", Recipe: "Melty Omelette Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "10", Soybeans: "0", Potato: "0", Tomato: "6", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '8', Type: "Curries/Stews", Recipe: "Soft Potato Chowder", Apple: "0", Honey: "0", Milk: "10", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "8", Tomato: "0", Mushroom: "4", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "22",  },
  { key: '9', Type: "Curries/Stews", Recipe: "Spore Mushroom Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "9", Tomato: "0", Mushroom: "14", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '10', Type: "Curries/Stews", Recipe: "Bulk Up Bean Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "4", Soybeans: "12", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "4", Leek: "0", Corn: "0", Sausage: "6", Total_ingredients: "26",  },
  { key: '11', Type: "Curries/Stews", Recipe: "Limber Corn Stew", Apple: "0", Honey: "0", Milk: "8", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "8", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "14", Sausage: "0", Total_ingredients: "30",  },
  { key: '12', Type: "Curries/Stews", Recipe: "Spicy Leek Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "10", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "8", Leek: "14", Corn: "0", Sausage: "0", Total_ingredients: "32",  },
  { key: '13', Type: "Curries/Stews", Recipe: "Grilled Tail Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "8", Herb: "25", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "33",  },
  { key: '14', Type: "Curries/Stews", Recipe: "Egg Bomb Curry", Apple: "11", Honey: "12", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "8", Soybeans: "0", Potato: "4", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '15', Type: "Curries/Stews", Recipe: "Ninja Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "24", Potato: "0", Tomato: "0", Mushroom: "5", Tail: "0", Herb: "0", Leek: "12", Corn: "0", Sausage: "9", Total_ingredients: "50",  },
  { key: '16', Type: "Curries/Stews", Recipe: "Dream Eater Butter Curry", Apple: "0", Honey: "0", Milk: "10", Ginger: "0", Oil: "0", Cacao: "12", Egg: "0", Soybeans: "0", Potato: "18", Tomato: "15", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "55",  },
  { key: '17', Type: "Curries/Stews", Recipe: "Inferno Corn Keema Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "12", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "27", Leek: "0", Corn: "14", Sausage: "24", Total_ingredients: "77",  },
  { key: '18', Type: "Salads", Recipe: "Bean Ham Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "8", Total_ingredients: "8",  },
  { key: '19', Type: "Salads", Recipe: "Snoozy Tomato Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "8", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "8",  },
  { key: '20', Type: "Salads", Recipe: "Fancy Apple Salad", Apple: "8", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "8",  },
  { key: '21', Type: "Salads", Recipe: "Immunity Leek Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "5", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "10", Corn: "0", Sausage: "0", Total_ingredients: "15",  },
  { key: '22', Type: "Salads", Recipe: "Snow Cloak Caesar Salad", Apple: "0", Honey: "0", Milk: "10", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "6", Total_ingredients: "16",  },
  { key: '23', Type: "Salads", Recipe: "Water Veil Tofu Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "15", Potato: "0", Tomato: "9", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "24",  },
  { key: '24', Type: "Salads", Recipe: "Heat Wave Tofu Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "10", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "6", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '25', Type: "Salads", Recipe: "Fury Attack Corn Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "8", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "9", Sausage: "0", Total_ingredients: "17",  },
  { key: '26', Type: "Salads", Recipe: "Superpower Extreme Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "6", Oil: "0", Cacao: "0", Egg: "5", Soybeans: "0", Potato: "3", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "9", Total_ingredients: "23",  },
  { key: '27', Type: "Salads", Recipe: "Moomoo Caprese Salad", Apple: "0", Honey: "0", Milk: "12", Ginger: "0", Oil: "5", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "6", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '28', Type: "Salads", Recipe: "Contrary Chocolate Meat Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "14", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "9", Total_ingredients: "23",  },
  { key: '29', Type: "Salads", Recipe: "Dazzling Apple Cheese Salad", Apple: "15", Honey: "0", Milk: "5", Ginger: "0", Oil: "3", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '30', Type: "Salads", Recipe: "Slowpoke Tail Pepper Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "5", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "10", Herb: "10", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "25",  },
  { key: '31', Type: "Salads", Recipe: "Spore Mushroom Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "8", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "8", Mushroom: "17", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "33",  },
  { key: '32', Type: "Salads", Recipe: "Overheat Ginger Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "10", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "8", Mushroom: "0", Tail: "0", Herb: "17", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '33', Type: "Salads", Recipe: "Gluttony Potato Salad", Apple: "6", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "9", Soybeans: "0", Potato: "14", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "7", Total_ingredients: "36",  },
  { key: '34', Type: "Salads", Recipe: "Calm Mind Fruit Salad", Apple: "21", Honey: "16", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "12", Sausage: "0", Total_ingredients: "49",  },
  { key: '35', Type: "Salads", Recipe: "Ninja Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "11", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "19", Potato: "0", Tomato: "0", Mushroom: "12", Tail: "0", Herb: "0", Leek: "15", Corn: "0", Sausage: "0", Total_ingredients: "57",  },
  { key: '36', Type: "Salads", Recipe: "Greengrass Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "22", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "9", Tomato: "14", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "17", Sausage: "0", Total_ingredients: "62",  },
  { key: '37', Type: "Desserts/Drinks", Recipe: "Warm Moomoo Milk", Apple: "0", Honey: "0", Milk: "7", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '38', Type: "Desserts/Drinks", Recipe: "Fancy Apple Juice", Apple: "8", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "8",  },
  { key: '39', Type: "Desserts/Drinks", Recipe: "Craft Soda Pop", Apple: "0", Honey: "9", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "9",  },
  { key: '40', Type: "Desserts/Drinks", Recipe: "Fluffy Sweet Potatoes", Apple: "0", Honey: "0", Milk: "5", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "9", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "14",  },
  { key: '41', Type: "Desserts/Drinks", Recipe: "Cloud Nine Soy Cake", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "8", Soybeans: "7", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "15",  },
  { key: '42', Type: "Desserts/Drinks", Recipe: "Ember Ginger Tea", Apple: "7", Honey: "0", Milk: "0", Ginger: "9", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '43', Type: "Desserts/Drinks", Recipe: "Lucky Chant Apple Pie", Apple: "12", Honey: "0", Milk: "4", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '44', Type: "Desserts/Drinks", Recipe: "Stalwart Vegetable Juice", Apple: "7", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "9", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '45', Type: "Desserts/Drinks", Recipe: "Huge Power Soy Donuts", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "12", Cacao: "7", Egg: "0", Soybeans: "16", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '46', Type: "Desserts/Drinks", Recipe: "Petal Dance Chocolate Tart", Apple: "11", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "11", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "22",  },
  { key: '47', Type: "Desserts/Drinks", Recipe: "Hustle Protein Smoothie", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "8", Egg: "0", Soybeans: "15", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '48', Type: "Desserts/Drinks", Recipe: "Big Malasada", Apple: "0", Honey: "6", Milk: "7", Ginger: "0", Oil: "10", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '49', Type: "Desserts/Drinks", Recipe: "Sweet Scent Chocolate Cake", Apple: "0", Honey: "9", Milk: "7", Ginger: "0", Oil: "0", Cacao: "8", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "24",  },
  { key: '50', Type: "Desserts/Drinks", Recipe: "Steadfast Ginger Cookies", Apple: "0", Honey: "14", Milk: "0", Ginger: "12", Oil: "0", Cacao: "5", Egg: "4", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '51', Type: "Desserts/Drinks", Recipe: "Lovely Kiss Smoothie", Apple: "11", Honey: "7", Milk: "9", Ginger: "0", Oil: "0", Cacao: "8", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '52', Type: "Desserts/Drinks", Recipe: "Neroli's Restorative Tea", Apple: "15", Honey: "0", Milk: "0", Ginger: "11", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "9", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '53', Type: "Desserts/Drinks", Recipe: "Explosion Popcorn", Apple: "0", Honey: "0", Milk: "7", Ginger: "0", Oil: "14", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "15", Sausage: "0", Total_ingredients: "36",  },
  { key: '54', Type: "Desserts/Drinks", Recipe: "Jigglypuff's Fruity Flan", Apple: "10", Honey: "20", Milk: "10", Ginger: "0", Oil: "0", Cacao: "0", Egg: "15", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "55",  },
  { key: '55', Type: "Desserts/Drinks", Recipe: "Teatime Corn Scones", Apple: "20", Honey: "0", Milk: "9", Ginger: "20", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "18", Sausage: "0", Total_ingredients: "67",  },
  { key: '56', Type: "Desserts/Drinks", Recipe: "Flower Gift Macarons", Apple: "0", Honey: "17", Milk: "10", Ginger: "0", Oil: "0", Cacao: "25", Egg: "25", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "77",  },
  { key: '57', Type: "Curries/Stews", Recipe: "Dizzy Punch Spicy Curry", Apple: "0", Honey: "11", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "11", Leek: "0", Corn: "0", Sausage: "0", Coffee: "11", Total_ingredients: "33",  },
  { key: '58', Type: "Curries/Stews", Recipe: "Hidden Power Perk-Up Stew", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "28", Potato: "0", Tomato: "25", Mushroom: "23", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Coffee: "16", Total_ingredients: "?",  },
  { key: '59', Type: "Salads", Recipe: "Defiant Coffee-Dressed Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "22", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "22", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "28", Coffee: "28", Total_ingredients: "?",  },
  { key: '60', Type: "Salads", Recipe: "Cross Chop Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "20", Soybeans: "0", Potato: "0", Tomato: "10", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "11", Sausage: "15", Coffee: "0", Total_ingredients: "?",  },
  { key: '61', Type: "Desserts/Drinks", Recipe: "Early Bird Coffee Jelly", Apple: "0", Honey: "12", Milk: "14", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Coffee: "16", Total_ingredients: "?",  },
  { key: '62', Type: "Desserts/Drinks", Recipe: "Zing Zap Spiced Cola", Apple: "35", Honey: "0", Milk: "0", Ginger: "20", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "20", Corn: "0", Sausage: "0", Coffee: "12", Total_ingredients: "?",  },
]
